matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-11
            - clang-12
      language: cpp
      dist: focal
      compiler:
        - gcc
        - clang

script:
  - bash ./.travis.sh
