matrix:
  include:
    - os: linux
      dist: focal
      
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install g++-11
  - sudo apt-get -y install clang-11

script:
  - bash ./.travis.sh
