matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - clang-10
      language: cpp
      dist: bionic
      compiler:
        - gcc
        - clang

script:
  - bash ./.travis.sh
