matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - groovy-devel
          packages:
            - g++-10
            - clang-11
      language: cpp        
      dist: bionic
      compiler:
        - gcc
        - clang

script:
  - bash ./.travis.sh
